# Generated by Django 4.2.1 on 2023-06-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_alter_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='reciepient',
        ),
    ]
